## specify build context here

version: "3"
 
services:
 
  # GISS Surface Temperature Analysis (GISTEMP)
  cli_035:
    image: dockermaterials_cli_035
    # This option now unsupported for v3: container_name: cli_035
    deploy:
      mode: replicated
      replicas: 2
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

  # Hazard Mapping System (HMS) Fire and Smoke Analysis
  cli_037:
    image: dockermaterials_cli_037
    # This option now unsupported for v3: container_name: cli_037
    deploy:
      mode: replicated
      replicas: 2
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3