neo4j:
  image: neo4j:3.3
  ports:
    - "7474"
    - "7687"
  environment:
    NEO4J_AUTH: none
    NEO4J_dbms_allow__upgrade: "true"
    # NEO4J_dbms_memory_pagecache_size: "2G"
    # NEO4J_dbms_memory_heap_maxSize: "4G"
    # NEO4J_apoc_export_file_enabled: "true"
